# FILE: pubspec.yaml
name: money_mentor
description: MoneyMentor — See. Compare. Optimize. Offline-first financial coach Flutter MVP.
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & utils
  cupertino_icons: ^1.0.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # State management
  riverpod: ^2.3.10
  flutter_riverpod: ^2.3.7

  # Database (Drift)
  drift: ^2.28.1
  drift_flutter: ^0.2.6
  path_provider: ^2.0.15
  path: ^1.8.3

  # Charts & visualization
  fl_chart: ^0.68.0

  # Exports & printing
  csv: ^5.0.0
  pdf: ^3.9.0
  printing: ^5.10.5

  # Security & local auth
  local_auth: ^2.1.6
  shared_preferences: ^2.1.1

  # JSON / codegen runtime annotations (MUST be in dependencies)
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Codegen tools
  build_runner: ^2.4.6
  drift_dev: ^2.28.3
  freezed: ^3.1.0
  json_serializable: ^6.6.1

  # Mocks & integration
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/seeded_categories.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
