// FILE: pubspec.yaml
name: money_mentor
description: MoneyMentor — See. Compare. Optimize. Offline-first financial coach Flutter MVP.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.0.0
  flutter_riverpod: ^2.0.0
  drift: ^2.0.0
  drift_flutter: ^2.0.0
  path_provider: ^2.0.0
  path: ^1.8.0
  fl_chart: ^0.60.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  csv: ^5.0.0
  pdf: ^3.8.0
  printing: ^5.10.0
  local_auth: ^2.1.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  drift_dev: ^2.0.0
  mockito: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

